services:
  vertx-crud-demo:
    container_name: vertx-crud-demo
    build:
      context: ..
      dockerfile: ./container/Dockerfile.jvm
    ports:
      - "8810:8810"
    networks:
      - sql-database

networks:
  sql-database:
    name: sql-database-network
    external: true